<?php
session_start();
require(dirname(__FILE__).'/MyBdd.php');

$bdd = MyBdd::Instance();
session_unset(); 
?>

<html>
<head>
	<title><?php echo $title; ?></title>
	<script type="text/javascript">
	alert("OOOOOOOOOOOOOOOOOOOOOOOOOOWEWAWAAAAAAAAWEWAWAAAAAA\n\
		AAAAAAAAWAWAWAAAA\n\
		OHOHOHOOOOOOOOOOOOOOOOOOOOOO \n\
		OHEWAWAWAWAWAAAAAAAAAAAAAA");

	alert("WEWEWEWEWE HOHOHO HOHOHO\n\
		WEWEWEWEWE HOHOHO \n\
		HOHOHOOOOOOOOOOOOOOOOOOOOOOOOOOOOHOHOHOHOOOOOOOOOO\n\
		OOOOOOOOO");

	alert("LALALALALALALAAAAAAAAAAAA...\n\
		LALALLA LALALAAA LAAAAAAAAAAAAAAAA \n\
		LALALAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n");

	alert("LALALALAAAAAAAAAAAAA\n\
		LALALALALAAAAAAAAAA\n\
		LOLOLOLOOOOOOOOOOOOOOOOOOOOOO LALALALAAAAAAAAAAAAAAAA \n\
		LOLAAAAAAAAA OHHOHOHOHOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO OHOHOOHOHO");
	alert("HOHOHOOOOOOOO\n\
		A IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII.. \n\
		la lala la la lala lala la la... OLOLOLO \n\
		PAPOLOLOPALO HELALOOOOOOOOOOOOOO");

	alert("LOLOLOLOLOLOLO... LOLOLOLOLOLO LOLOLOLOLO LOLLLO");

	alert("HOHOHOHOHO ! HOHOHOHOHO ! HOHOHOHOHO ! HOHOHOHOHO !\n\
		LALALALOLOLAOLOALAOLAALOALAOLOOOOO ! \n\
		AAAAAAAAAAAAAAAAAAAAAAH OWOLOOOOOOOOO ");
	alert("LALALOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOLA\n\
		ALOOOOOO");

	alert("OHOHOHOHOOOOOOOOOOOO LALALOOOOOOOOOOOOOOOOOOOOOOOOO \n\
		HOOOOOOOOOOOOOWIWOOOOOOO.... LOLOLOLOLOLO OHOHOHOOOOOOOOOOOOOOOOOO...");
	alert("LOLOLOLOLOLO OOOOOHOHOHOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n\
		OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO");
	alert("OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n\
		OOOOOOOOOOOOOOOOOOOOOOOOOOOOO");
	</script>
</head>
<body>
	<div style="width:500px; margin:auto;">
		<h1>Trop tard</h1>
		<label>Tu dois te reconnecter <a href="index.php">Ici</a> :P</label>
		<img src="user/trololo.jpg"/>
	</div>
</body>
</html>